### ISSUE TITLE
CoroutineMock object is not iterable

### ISSUE THREAD

**Issue by argaen** [Martiusweb/asynctest#27]
Hi, I installed ubuntu 16.10 which comes with Python version: Python 3.5.2 (default, Sep 10 2016, 08:21:44). Running the same tests that were previously working returns the following error:

```python
    @functools.wraps(func)
    def coro(*args, **kw):
        res = func(*args, **kw)
        if (futures.isfuture(res) or inspect.isgenerator(res) or
            isinstance(res, CoroWrapper)):
>           res = yield from res
E           TypeError: 'CoroutineMock' object is not iterable
```

Any ideas?

**Comment by Martiusweb** [comment]
Hi,
Which version of asynctest were you using before and which one are you
using now? Can you show me a code sample that I can run to reproduce the
error?

Le sam. 12 nov. 2016 4:47 PM, Manuel Miranda <notifications@github.com> a
écrit :

Hi, I installed ubuntu 16.10 which comes with Python version: Python 3.5.2
(default, Sep 10 2016, 08:21:44). Running the same tests that were
previously working returns the following error:

    @functools.wraps(func)
    def coro(*args, **kw):
        res = func(*args, **kw)
        if (futures.isfuture(res) or inspect.isgenerator(res) or
            isinstance(res, CoroWrapper)):>           res = yield from
resE           TypeError: 'CoroutineMock' object is not iterable

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Martiusweb/asynctest/issues/27>, or mute the thread

**Comment by argaen** [comment]
asynctest version is asynctest==0.9.0 (didnt change the version with the update). I've built a reduced code sample:

```python
import pytest

from asynctest import CoroutineMock

async def my_method():
    return await CoroutineMock().get()


@pytest.mark.asyncio
async def test_example():
    await my_method()
```

The error:

```bash
(aiocache)blck@ember:~$ pytest omg.py 
==================================================================== test session starts =====================================================================
platform linux -- Python 3.5.2, pytest-3.0.4, py-1.4.31, pluggy-0.4.0
rootdir: /home/blck, inifile: 
plugins: mock-1.4.0, cov-2.4.0, asyncio-0.5.0
collected 1 items 

omg.py F

========================================================================== FAILURES ==========================================================================
________________________________________________________________________ test_example ________________________________________________________________________

    @pytest.mark.asyncio
    async def test_example():
>       await my_method()

omg.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
omg.py:6: in my_method
    return await CoroutineMock().get()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (), kw = {}, res = <CoroutineMock name='mock..' id='140343096127440'>

    @functools.wraps(func)
    def coro(*args, **kw):
        res = func(*args, **kw)
        if (futures.isfuture(res) or inspect.isgenerator(res) or
            isinstance(res, CoroWrapper)):
>           res = yield from res
E           TypeError: 'CoroutineMock' object is not iterable

/usr/lib/python3.5/asyncio/coroutines.py:209: TypeError
```

The thing is that in travis this runs well: https://travis-ci.org/argaen/aiocache (just showing the tests are passing) but when running in my computer, they fail with the above error.

**Comment by Martiusweb** [comment]
CoroutineMock mocks a coroutine function. In order to get a coroutine instance (which can be awaited), you must call it: 

    >>> asynctest.CoroutineMock()
    <CoroutineMock id='140264440632320'>
    >>> asynctest.CoroutineMock()()
    <generator object CoroutineMock._mock_call.<locals>.<lambda> at 0x7f91dc2727d8>

Since a coroutine function has no get() method, it seems normal that the result is not an awaitable object.

Can you tell me which test in aiocache is failing, and what I need to run to execute it?
I cloned your repository and ran the tests (following the instructions from your .travisci.yml file), and only one test failed, but not related to anything mocked:

    TestRedisBackend.test_raw

    self = <integration.backends.test_redis.TestRedisBackend object at 0x7f48f4d71c88>
    redis_cache = RedisCache (127.0.0.1:6379)

        @pytest.mark.asyncio
        async def test_raw(self, redis_cache):
            await redis_cache.raw('set', b"key", b"value")
            assert await redis_cache.raw("get", b"key") == b"value"
    >       assert await redis_cache.raw("keys", "k*") == [b"key"]
    E       assert [b'key', b'ke...ey4', b'key3'] == [b'key']

**Comment by argaen** [comment]
The tests failing are the ones run by `make ut`. An example test failing:

```python

_________________________________________________________________ TestMockCache.test_delete __________________________________________________________________

self = <ut.test_cache.TestMockCache object at 0x7f91a176c7f0>, mock_cache = <aiocache.cache.BaseCache object at 0x7f91a1758780>

    @pytest.mark.asyncio
    async def test_delete(self, mock_cache):
>       await mock_cache.delete(pytest.KEY)

tests/ut/test_cache.py:110: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
aiocache/cache.py:223: in delete
    return await asyncio.wait_for(self._delete(key, namespace), timeout=self._timeout)
/usr/lib/python3.5/asyncio/tasks.py:393: in wait_for
    return fut.result()
/usr/lib/python3.5/asyncio/futures.py:292: in result
    raise self._exception
/usr/lib/python3.5/asyncio/tasks.py:239: in _step
    result = coro.send(None)
aiocache/cache.py:228: in _delete
    ret = await self._backend.delete(ns_key)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (), kw = {}, res = <CoroutineMock name='mock..' id='140263456431072'>

    @functools.wraps(func)
    def coro(*args, **kw):
        res = func(*args, **kw)
        if (futures.isfuture(res) or inspect.isgenerator(res) or
            isinstance(res, CoroWrapper)):
>           res = yield from res
E           TypeError: 'CoroutineMock' object is not iterable

/usr/lib/python3.5/asyncio/coroutines.py:209: TypeError
```

As I said test pass in travis and passing before updating ubuntu version (which I guess changes python3.5 version?).

**Comment by Martiusweb** [comment]
Sorry but I still can't reproduce, I'm using python 3.5.2, asynctest 0.9.0, and running make ut after building a repository.

Anyway, looking at your code, I think that you are not using asynctest correctly: you should almost never use CoroutineMock directly, since it's only a mock of a coroutine function. For instance:

    mocked_cache = CoroutineMock(spec=BaseCache)

should be:

    mocked_cache = Mock(spec=BaseCache)

and ``mocked_cache.add`` will be a CoroutineMock instance, since ``BaseCase.add`` is a coroutine function.

This one looks suspicious too:

    mocker.patch('aiocache.cache.BaseCache.get_backend', return_value=asynctest.CoroutineMock())

as in your code (aiocache/cache.py) ``get_backend`` doesn't return a coroutine function.

**Comment by argaen** [comment]
Ahhh I see. Thanks for the explanation, understood it correctly now. I've fixed it in the code but its failing anyway in the laptop I did the upgrade.

I'll try to investigate what is the problem

**Comment by Martiusweb** [comment]
Is the issue still related to asynctest or can we close the issue?

**Comment by argaen** [comment]
We can close the issue. If I find its related with asynctest Ill continue
the discussion here :)

**Comment by argaen** [comment]
Okay, I've been debugging a bit more because I was getting the exact same error in Python3.6:
```python
tests/ut/test_cache.py::TestCache::test_get FAILED

===================================================================================== FAILURES ======================================================================================
________________________________________________________________________________ TestCache.test_get _________________________________________________________________________________



pyfuncitem = <Function 'test_get'>

    @pytest.mark.tryfirst
    def pytest_pyfunc_call(pyfuncitem):
        """
        Run asyncio marked test functions in an event loop instead of a normal
        function call.
        """
        for marker_name, fixture_name in _markers_2_fixtures.items():
            if marker_name in pyfuncitem.keywords:
                event_loop = pyfuncitem.funcargs[fixture_name]

                funcargs = pyfuncitem.funcargs
                testargs = {arg: funcargs[arg]
                            for arg in pyfuncitem._fixtureinfo.argnames}
                event_loop.run_until_complete(
>                   asyncio.async(pyfuncitem.obj(**testargs), loop=event_loop))

../../.pyenv/versions/3.6.0b3/envs/aiocache36/lib/python3.6/site-packages/pytest_asyncio/plugin.py:77:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.pyenv/versions/3.6.0b3/lib/python3.6/asyncio/base_events.py:449: in run_until_complete
    return future.result()
aiocache/cache.py:105: in get
    await self._policy.pre_get(self, key)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (), kw = {}, res = <CoroutineMock name='mock..' id='4472521448'>

    @functools.wraps(func)
    def coro(*args, **kw):
        res = func(*args, **kw)
        if (base_futures.isfuture(res) or inspect.isgenerator(res) or
            isinstance(res, CoroWrapper)):
>           res = yield from res
E           TypeError: 'CoroutineMock' object is not iterable

../../.pyenv/versions/3.6.0b3/lib/python3.6/asyncio/coroutines.py:209: TypeError
============================================================================= 1 failed in 0.16 seconds ==============================================================================
```

`isfuture` expects an iterable and decides it is a future by checking the [`_asyncio_future_blocking`](https://github.com/python/asyncio/blob/ae82bb7960cb13f877949c8f2dbbbc2133f40b68/asyncio/futures.py#L120) attribute. Since the class its a Mock, this evaluates to True and there we have the crash.

By adding `self._asyncio_future_blocking = None` in the `CoroutineMock` definition the test is passing but some others are still crashing, need to investigate a bit more.

**Comment by Martiusweb** [comment]
asyncio.isfuture() has been added very recently to asyncio, I didn't know it was already merged in python 3.6 beta.

I'm working on the support of python 3.6 in a branch that I'll merge (and then release a new version of asynctest) once python 3.6 will be released (or maybe after one or two RCs). I can work on the support of isfuture() in a few days (it shouldn't be too much work).

**Comment by argaen** [comment]
I still don't explain why the other laptops python 3.5 version was giving the very same error (if you check the traceback I posted in the first message, there is also the `isfuture` call). Maybe the version is corrupted or dunno, have to check the exact version I have.

Im working on another issue for my current milestone but once I finish it if there is no patch Ill give it a chance to provide one myself :). Thank you for your time! :)

**Comment by Martiusweb** [comment]
According to https://github.com/python/asyncio/commit/ae82bb7960cb13f877949c8f2dbbbc2133f40b68, asyncio.isfuture() supports mock objects, and it seems to be the case when I test it:

>>> import asyncio, asynctest
>>> asyncio.isfuture(asynctest.CoroutineMock())
False
>>> asyncio.isfuture(asynctest.Mock(asyncio.Future))
True

Are you using development versions of asyncio?

During the last weeks, there was a lot of activity on asyncio, especially iscoroutine(), isfuture(), and the Future class. asynctest is already full of workarounds and hacks which are quite painful to maintain, thus, asynctest should only target stable releases. We can watch asyncio for breaking changes and try to patch them upstream before a release.

**Comment by argaen** [comment]
I was trying with Python3.6r3. But sure, if you think that when Python3.6 is officially released there won't be a problem we can just wait :).

**Comment by mborho** [comment]
Had the same issue after upgrading to Ubuntu 16.10 / Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 

By adding **spec=** parameter to Mock() where needed, and by defining a **return_value** for every CoroutineMock everything works again...

**Comment by Martiusweb** [comment]
Thanks for the info, I reopen the issue. I hope I'll find time to work on it this week.

I remember that I haven't been able to reproduce it with a vanilla python 3.5.2.
Can you check if you're using the release of asyncio bundled with python 3.5.2 or if you installed a more recent version, via pip or a package specific to ubuntu?

**Comment by mborho** [comment]
@Martiusweb For me, it onyl happens with "Python 3.5.2+ (default, Sep 22 2016, 12:18:14)" on Ubuntu 16.10.  Running the tests in a plain ubuntu 16.10 docker image reproduces the problem for me. Using python-virtualenv, python3-pip from apt.

**Comment by Martiusweb** [comment]
Ubuntu 16.10 should run python 3.5.1 according to: http://packages.ubuntu.com/yakkety/python3

This "+" after the version seems to indicate that it's not the vanilla release, thus I guess some patches were backported in the package you're using.

I'm working on the compatibility of asynctest with Python 3.6, it will probably solve the issue. You can test the compat_py36 branch: it's still a work in progress but the fix may already be there.

**Comment by Martiusweb** [comment]
My own tests are working with Python 3.6 when using the compat_py36 branch. I'd like to get more feedback before I merge it into master and make a new release.

Can you test your projects with this branch?

**Comment by argaen** [comment]
I'm having a different error now:
```python
_______________________________________________________________ TestCache.test_clear_timeouts ________________________________________________________________

self = <ut.test_cache.TestCache object at 0x7f506565a400>, mock_cache = <ut.conftest.MockCache object at 0x7f5065612898>

    @pytest.mark.asyncio
    async def test_clear_timeouts(self, mock_cache):
        mock_cache._clear = asynctest.CoroutineMock(side_effect=asyncio.sleep(0.005))
    
        with pytest.raises(asyncio.TimeoutError):
>           await mock_cache.clear(pytest.KEY)

tests/ut/test_cache.py:183: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
aiocache/plugins.py:16: in wrapper
    ret = await func(self, *args, **kwargs)
aiocache/cache.py:252: in clear
    ret = await self._clear(namespace)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (), kw = {}, res = <Future pending>

    @functools.wraps(func)
    def coro(*args, **kw):
        res = func(*args, **kw)
        if (base_futures.isfuture(res) or inspect.isgenerator(res) or
            isinstance(res, CoroWrapper)):
>           res = yield from res
E           AssertionError: yield from wasn't used with future

../../.pyenv/versions/3.6-dev/lib/python3.6/asyncio/coroutines.py:213: AssertionError
```

I'm using python3.6-dev (the one installed from pyenv) and installed -e git+git@github.com:Martiusweb/asynctest.git@1640c537891ff74f1c769152381facf118c146c8#egg=asynctest

**Comment by argaen** [comment]
I've solved it by creating a fake function myself without CoroutineMock, seems that it doesnt like the `mock_cache._expire = asynctest.CoroutineMock(side_effect=asyncio.sleep(0.005))`.

**Comment by Martiusweb** [comment]
I'm still trying to know why it worked and doesn't work anymore, but I suspect that it shouldn't have worked at all, your solution is probably the right one.

    asynctest.CoroutineMock(side_effect=asyncio.sleep(0.005))

means "mock a coroutine which returns ``asyncio.sleep(0.005)``, like:

    async def dummy():
        return asyncio.sleep(.005)   # without await

I wonder if before python 3.6, asyncio.sleep(0.005) was never awaited, and since the sleep time is really low, it wasn't really noticeable.

Anyway, sorry for taking that long to look at it, I just moved to a new job (which makes me busy!).

Once I figured it all out, I'll to merge the branch and release the new version.

**Comment by argaen** [comment]
> I wonder if before python 3.6, asyncio.sleep(0.005) was never awaited, and since the sleep time is really low, it wasn't really noticeable.

If this didn't work, my tests wouldn't pass because they were actually expecting the `TimeoutError` to trigger so it must be something else...

No worries :). Right know I'm just monkeypatching the function directly and works. If you find the problem then I'll be happy to test the branch before merging.

**Comment by Martiusweb** [comment]
Feeding side_effect of CoroutineMock() with an old style coroutine doesn't work. In fact, according to the doc of CoroutineMock, side_effect doesn't expect a coroutine. I should have seen that in your case sooner!

The intended use was:
   coro = asynctest.CoroutineMock(side_effect=["foo", "bar"])
   await coro()  # returns "foo"
   await coro()  # returns "bar"

side_effect expects either a function (not a coroutine) or an iterable (list or generator, for instance).

If an old-style coroutine is used, it will be treated as a generator and return whatever is yielded.
asyncio.sleep() "yields from" a future, which (as seen in Future.__iter__) yields itself until done. This is why it works with 3.5.

I suppose that since the case is undocumented, it's safe to merge and release the new version without the support of side_effect yet. I opened the issue #31 for this.

**Comment by argaen** [comment]
Yeah, I just extrapolated that I would be able to use `side_effect` with a coroutine and since it worked when I tried it...

Makes sense since its a different issue.

**Comment by rvangraan** [comment]
Here is a test case that shows the problem and how to work around this problem:
```
import asynctest
import asyncio

async def default_mock():
    return asynctest.CoroutineMock()

class MyTest:
    def __init__(self, foo):
        self._foo = foo

    async def call_foo(self):
        return await self._foo()

class Tests(asynctest.TestCase):

    def test_will_fail(self):
        async_mock = asynctest.CoroutineMock()
        my_test_object = MyTest(async_mock)
        l = asyncio.get_event_loop()
        res =  l.run_until_complete(my_test_object.call_foo())
        print(res)

    def test_will_succeed(self):
        async_mock = asynctest.CoroutineMock()
        async_mock.side_effect = default_mock
        my_test_object = MyTest(async_mock)

        l = asyncio.get_event_loop()
        res =  l.run_until_complete(my_test_object.call_foo())
        print(res)
```
Produces:

```
========================================== test session starts ===========================================
platform linux -- Python 3.6.0b2, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /root, inifile:
plugins: mock-1.6.3, asyncio-0.7.0
collected 2 items

test_async.py F.

================================================ FAILURES ================================================
__________________________________________ Tests.test_will_fail __________________________________________

self = <test_async.Tests testMethod=test_will_fail>

    def test_will_fail(self):
        async_mock = asynctest.CoroutineMock()
        my_test_object = MyTest(async_mock)
        l = asyncio.get_event_loop()
>       res =  l.run_until_complete(my_test_object.call_foo())

test_async.py:20:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.6/dist-packages/asynctest/case.py:202: in wrapper
    return method(*args, **kwargs)
/usr/lib/python3.6/asyncio/base_events.py:449: in run_until_complete
    return future.result()
/usr/lib/python3.6/asyncio/tasks.py:239: in _step
    result = coro.send(None)
test_async.py:12: in call_foo
    return await self._foo()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (), kw = {}, res = <CoroutineMock id='140440721093352'>

    @functools.wraps(func)
    def coro(*args, **kw):
        res = func(*args, **kw)
        if (futures.isfuture(res) or inspect.isgenerator(res) or
            isinstance(res, CoroWrapper)):
>           res = yield from res
E           TypeError: 'CoroutineMock' object is not iterable

/usr/lib/python3.6/asyncio/coroutines.py:209: TypeError
=================================== 1 failed, 1 passed in 0.13 seconds ===================================
```
